---
stages:
- name: custom-image-jobs
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: customimage
    script: ls -al build
    docker_image: alpine
  - name: Test
    type: tester
    script: ls -al test
    test_type: customimage
    docker_image: alpine
  - name: Deploy
    type: deployer
    deploy_permission: DEV_IN_SPACE
    deploy_type: customimage
    script: ls -al deploy
    docker_image: alpine
    
