version: '2'

template:
  name: "custom-image-jobs"
  description: template for custom image jobs
  info:
    git url: >-
      [https://github.com/skaegi/custom-image-jobs](https://github.com/skaegi/custom-image-jobs)
toolchain:
  name: 'custom-image-jobs-{{timestamp}}'
services:
  build:
    service_id: pipeline
    parameters:
      services:
        - sample-repo
      name: custom-image-jobs
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml